// Export all DTOs
export * from './start-trip.dto';
export * from './arrive.dto';
export * from './start-inspection.dto';
export * from './complete-diagnosis.dto';
export * from './request-parts.dto';
export * from './not-fixed.dto';
export * from './pickup-device.dto';
export * from './complete-repair.dto';
export * from './update-location.dto';
export * from './send-message.dto';
export * from './start-repair.dto';
export * from './send-completion-otp.dto';
export * from './tasks-query.dto';
